USE DATABASE MINDSPHERE_TWIN_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE VIEW ANALYTICS.TELEMETRY_HOURLY_METRICS AS
WITH hourly AS (
    SELECT
        DATE_TRUNC('HOUR', "TIMESTAMP") AS HOUR_TS,
        ASSET_ID,
        METRIC_NAME,
        AVG(METRIC_VALUE) AS HOURLY_MEAN,
        VARIANCE(METRIC_VALUE) AS HOURLY_VARIANCE,
        MAX(IFF(STATUS = 'ALERT', 1, 0)) AS HAS_ALERT
    FROM RAW.RAW_TELEMETRY
    GROUP BY 1, 2, 3
),
windowed AS (
    SELECT
        HOUR_TS,
        ASSET_ID,
        METRIC_NAME,
        HOURLY_MEAN,
        HOURLY_VARIANCE,
        HOURLY_MEAN - LAG(HOURLY_MEAN) OVER (
            PARTITION BY ASSET_ID, METRIC_NAME
            ORDER BY HOUR_TS
        ) AS DELTA_1H,
        AVG(HOURLY_MEAN) OVER (
            PARTITION BY ASSET_ID, METRIC_NAME
            ORDER BY HOUR_TS
            ROWS BETWEEN 3 PRECEDING AND CURRENT ROW
        ) AS MOVING_AVG_4H,
        VARIANCE(HOURLY_MEAN) OVER (
            PARTITION BY ASSET_ID, METRIC_NAME
            ORDER BY HOUR_TS
            ROWS BETWEEN 7 PRECEDING AND CURRENT ROW
        ) AS MOVING_VAR_8H,
        HAS_ALERT
    FROM hourly
)
SELECT *
FROM windowed;

CREATE OR REPLACE VIEW ANALYTICS.TEMPORAL_STATE_CHUNKS AS
WITH pivoted AS (
    SELECT
        HOUR_TS,
        ASSET_ID,
        MAX(IFF(METRIC_NAME = 'temperature', HOURLY_MEAN, NULL)) AS TEMPERATURE_CURRENT,
        MAX(IFF(METRIC_NAME = 'temperature', MOVING_AVG_4H, NULL)) AS TEMPERATURE_MOVING_AVG_4H,
        MAX(IFF(METRIC_NAME = 'temperature', MOVING_VAR_8H, NULL)) AS TEMPERATURE_MOVING_VAR_8H,
        MAX(IFF(METRIC_NAME = 'temperature', DELTA_1H, NULL)) AS TEMPERATURE_DELTA_1H,
        MAX(IFF(METRIC_NAME = 'vibration', HOURLY_MEAN, NULL)) AS VIBRATION_CURRENT,
        MAX(IFF(METRIC_NAME = 'vibration', MOVING_AVG_4H, NULL)) AS VIBRATION_MOVING_AVG_4H,
        MAX(IFF(METRIC_NAME = 'vibration', MOVING_VAR_8H, NULL)) AS VIBRATION_MOVING_VAR_8H,
        MAX(IFF(METRIC_NAME = 'vibration', DELTA_1H, NULL)) AS VIBRATION_DELTA_1H,
        MAX(IFF(METRIC_NAME = 'pressure', HOURLY_MEAN, NULL)) AS PRESSURE_CURRENT,
        MAX(IFF(METRIC_NAME = 'pressure', MOVING_AVG_4H, NULL)) AS PRESSURE_MOVING_AVG_4H,
        MAX(IFF(METRIC_NAME = 'pressure', MOVING_VAR_8H, NULL)) AS PRESSURE_MOVING_VAR_8H,
        MAX(IFF(METRIC_NAME = 'pressure', DELTA_1H, NULL)) AS PRESSURE_DELTA_1H,
        MAX(HAS_ALERT) AS HAS_ANY_ALERT
    FROM ANALYTICS.TELEMETRY_HOURLY_METRICS
    GROUP BY 1, 2
),
state_with_events AS (
    SELECT
        p.*,
        e.LOG_ID AS NEAREST_PRIOR_LOG_ID,
        e.LOG_DATE AS NEAREST_PRIOR_LOG_DATE,
        e.ERROR_CODE AS NEAREST_PRIOR_ERROR_CODE,
        e.TECHNICIAN_NOTES AS NEAREST_PRIOR_TECHNICIAN_NOTES
    FROM pivoted p
    LEFT JOIN LATERAL (
        SELECT
            LOG_ID,
            LOG_DATE,
            ERROR_CODE,
            TECHNICIAN_NOTES
        FROM RAW.MAINTENANCE_LOGS m
        WHERE m.ASSET_ID = p.ASSET_ID
          AND m.LOG_DATE <= p.HOUR_TS
        ORDER BY m.LOG_DATE DESC
        LIMIT 1
    ) e ON TRUE
)
SELECT
    HOUR_TS,
    ASSET_ID,
    TEMPERATURE_CURRENT,
    TEMPERATURE_MOVING_AVG_4H,
    TEMPERATURE_MOVING_VAR_8H,
    TEMPERATURE_DELTA_1H,
    VIBRATION_CURRENT,
    VIBRATION_MOVING_AVG_4H,
    VIBRATION_MOVING_VAR_8H,
    VIBRATION_DELTA_1H,
    PRESSURE_CURRENT,
    PRESSURE_MOVING_AVG_4H,
    PRESSURE_MOVING_VAR_8H,
    PRESSURE_DELTA_1H,
    HAS_ANY_ALERT,
    NEAREST_PRIOR_LOG_ID,
    NEAREST_PRIOR_LOG_DATE,
    NEAREST_PRIOR_ERROR_CODE,
    NEAREST_PRIOR_TECHNICIAN_NOTES,
    OBJECT_CONSTRUCT(
        'hour_ts', HOUR_TS,
        'asset_id', ASSET_ID,
        'temperature', OBJECT_CONSTRUCT(
            'current', TEMPERATURE_CURRENT,
            'moving_avg_4h', TEMPERATURE_MOVING_AVG_4H,
            'moving_var_8h', TEMPERATURE_MOVING_VAR_8H,
            'delta_1h', TEMPERATURE_DELTA_1H
        ),
        'vibration', OBJECT_CONSTRUCT(
            'current', VIBRATION_CURRENT,
            'moving_avg_4h', VIBRATION_MOVING_AVG_4H,
            'moving_var_8h', VIBRATION_MOVING_VAR_8H,
            'delta_1h', VIBRATION_DELTA_1H
        ),
        'pressure', OBJECT_CONSTRUCT(
            'current', PRESSURE_CURRENT,
            'moving_avg_4h', PRESSURE_MOVING_AVG_4H,
            'moving_var_8h', PRESSURE_MOVING_VAR_8H,
            'delta_1h', PRESSURE_DELTA_1H
        ),
        'alert_state', HAS_ANY_ALERT,
        'nearest_prior_event', OBJECT_CONSTRUCT(
            'log_id', NEAREST_PRIOR_LOG_ID,
            'log_date', NEAREST_PRIOR_LOG_DATE,
            'error_code', NEAREST_PRIOR_ERROR_CODE,
            'technician_notes', NEAREST_PRIOR_TECHNICIAN_NOTES
        )
    ) AS TEMPORAL_STATE_PAYLOAD
FROM state_with_events;
