USE DATABASE MINDSPHERE_TWIN_DB;

CREATE SCHEMA IF NOT EXISTS SECURITY;
CREATE SCHEMA IF NOT EXISTS AUDIT;

CREATE OR REPLACE ROLE MS_TWIN_ADMIN;
CREATE OR REPLACE ROLE MS_TWIN_ENGINEER;
CREATE OR REPLACE ROLE MS_TWIN_OPERATOR;
CREATE OR REPLACE ROLE MS_TWIN_AUDITOR;

GRANT USAGE ON DATABASE MINDSPHERE_TWIN_DB TO ROLE MS_TWIN_ADMIN;
GRANT USAGE ON DATABASE MINDSPHERE_TWIN_DB TO ROLE MS_TWIN_ENGINEER;
GRANT USAGE ON DATABASE MINDSPHERE_TWIN_DB TO ROLE MS_TWIN_OPERATOR;
GRANT USAGE ON DATABASE MINDSPHERE_TWIN_DB TO ROLE MS_TWIN_AUDITOR;

GRANT USAGE ON SCHEMA RAW TO ROLE MS_TWIN_ADMIN;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MS_TWIN_ADMIN;
GRANT USAGE ON SCHEMA SECURITY TO ROLE MS_TWIN_ADMIN;
GRANT USAGE ON SCHEMA AUDIT TO ROLE MS_TWIN_ADMIN;

GRANT USAGE ON SCHEMA RAW TO ROLE MS_TWIN_ENGINEER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MS_TWIN_ENGINEER;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MS_TWIN_OPERATOR;
GRANT USAGE ON SCHEMA ANALYTICS TO ROLE MS_TWIN_AUDITOR;

GRANT SELECT ON ALL TABLES IN SCHEMA RAW TO ROLE MS_TWIN_ENGINEER;
GRANT SELECT ON ALL TABLES IN SCHEMA ANALYTICS TO ROLE MS_TWIN_ENGINEER;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE MS_TWIN_ENGINEER;

GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE MS_TWIN_OPERATOR;
GRANT SELECT ON TABLE ANALYTICS.RAG_AUDIT_LOG TO ROLE MS_TWIN_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA ANALYTICS TO ROLE MS_TWIN_AUDITOR;

GRANT INSERT ON TABLE ANALYTICS.RAG_AUDIT_LOG TO ROLE MS_TWIN_ENGINEER;
GRANT INSERT ON TABLE ANALYTICS.RAG_AUDIT_LOG TO ROLE MS_TWIN_ADMIN;

CREATE OR REPLACE MASKING POLICY SECURITY.TECH_NOTES_MASK_POLICY AS (val STRING) RETURNS STRING ->
    CASE
        WHEN CURRENT_ROLE() IN ('MS_TWIN_ADMIN', 'MS_TWIN_ENGINEER', 'MS_TWIN_AUDITOR') THEN val
        ELSE '[REDACTED: TECHNICIAN_NOTES]'
    END;

ALTER TABLE RAW.MAINTENANCE_LOGS
    MODIFY COLUMN TECHNICIAN_NOTES
    SET MASKING POLICY SECURITY.TECH_NOTES_MASK_POLICY;

CREATE OR REPLACE TABLE ANALYTICS.RAG_AUDIT_LOG (
    EVENT_TS TIMESTAMP_NTZ NOT NULL,
    ASSET_ID STRING NOT NULL,
    USER_PROMPT STRING NOT NULL,
    RETRIEVED_CONTEXT VARIANT,
    RECOMMENDATION_TEXT STRING,
    RETRIEVAL_QUALITY_SCORE FLOAT,
    SAFETY_STATUS STRING,
    SAFETY_DETAILS VARIANT,
    MODEL_NAME STRING,
    REQUESTOR_ROLE STRING DEFAULT CURRENT_ROLE(),
    REQUESTOR_USER STRING DEFAULT CURRENT_USER()
);

CREATE OR REPLACE VIEW AUDIT.RAG_SAFETY_AUDIT_DAILY AS
SELECT
    DATE_TRUNC('DAY', EVENT_TS) AS EVENT_DAY,
    ASSET_ID,
    COUNT(*) AS TOTAL_REQUESTS,
    AVG(RETRIEVAL_QUALITY_SCORE) AS AVG_RETRIEVAL_QUALITY,
    COUNT_IF(SAFETY_STATUS = 'PASS') AS SAFE_RESPONSES,
    COUNT_IF(SAFETY_STATUS = 'BLOCKED') AS BLOCKED_RESPONSES
FROM ANALYTICS.RAG_AUDIT_LOG
GROUP BY 1, 2
ORDER BY EVENT_DAY DESC, ASSET_ID;

GRANT SELECT ON VIEW AUDIT.RAG_SAFETY_AUDIT_DAILY TO ROLE MS_TWIN_AUDITOR;
GRANT SELECT ON VIEW AUDIT.RAG_SAFETY_AUDIT_DAILY TO ROLE MS_TWIN_ADMIN;
